### ISSUE TITLE
Allow addition of filters to dynatrace dashboard tiles for SLI/SLO generation

### ISSUE THREAD

**Issue by luisr-escobar** [keptn-contrib/dynatrace-sli-service#94] opened 2020-10-01 14:49 UTC
Tested with `version 0.5.0`

Currently filtering of entities for a dashboard only works with management zones but would be very useful to have the ability to add filters on a tile by tile basis. Currently if a tile contains filters the evaluation does not finish and the following logs are added to the dynatrace-sli-service pod:

```
Query all dashboards
--
  | Request finished, parsing dashboard list response body...
  | Analyzing if Dashboard matches: KQG;project=projectname;service=servicename;stage=environmentname
  | Found Dashboard Match: a5a7665c-2207-4707-9ab0-9eff03f9cac6
  | Query dashboard with ID: a5a7665c-2207-4707-9ab0-9eff03f9cac6
  | Request finished, parsing dashboard response body...
  | 2020/09/30 14:42:22 http: panic serving 10.248.0.1:54762: runtime error: invalid memory address or nil pointer dereference
goroutine 1435 [running]:
--
  | net/http.(*conn).serve.func1(0xc0000ce000)
  | /usr/local/go/src/net/http/server.go:1767 +0x139
  | panic(0x13819e0, 0x2081e30)
  | /usr/local/go/src/runtime/panic.go:679 +0x1b2
  | github.com/keptn-contrib/dynatrace-sli-service/pkg/lib/dynatrace.(*Handler).QueryDynatraceDashboardForSLIs(0xc0006b4d58, 0xc0004056e0, 0xe, 0xc0004056a9, 0x3, 0xc000405700, 0xe, 0x0, 0x0, 0x3d09000, ...)
  | /go/src/github.com/keptn-contrib/dynatrace-sli-service/pkg/lib/dynatrace/dynatrace.go:783 +0x395
  | main.getDataFromDynatraceDashboard(0xc000020d58, 0xc0001a8000, 0x3d09000, 0xed70657f9, 0x0, 0x137d9fc0, 0xed706580d, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/keptn-contrib/dynatrace-sli-service/cmd/main.go:159 +0x14c
  | main.retrieveMetrics(0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0xc0004242a0, 0x1706c00)
  | /go/src/github.com/keptn-contrib/dynatrace-sli-service/cmd/main.go:304 +0x782
  | main.gotEvent(0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0x0, 0x0)
  | /go/src/github.com/keptn-contrib/dynatrace-sli-service/cmd/main.go:86 +0xf9
  | reflect.Value.call(0x1354620, 0x15aa7c8, 0x13, 0x15088ae, 0x4, 0xc000424810, 0x2, 0x2, 0x40be3f, 0x14b60e0, ...)
  | /usr/local/go/src/reflect/value.go:460 +0x5f6
  | reflect.Value.Call(0x1354620, 0x15aa7c8, 0x13, 0xc000424810, 0x2, 0x2, 0xc0004242a0, 0xc0000311e0, 0x1)
  | /usr/local/go/src/reflect/value.go:321 +0xb4
  | github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*receiverFn).invoke(0xc0004fb200, 0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0xc0004246c0, 0x11d7f8b, ...)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/client/receiver.go:93 +0x220
  | github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*ceClient).obsReceive(0xc0002268c0, 0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0xc0004246c0, 0xc000031440, ...)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/client/client.go:132 +0xfc
  | github.com/cloudevents/sdk-go/pkg/cloudevents/client.(*ceClient).Receive(0xc0002268c0, 0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0xc0004246c0, 0x0, ...)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/client/client.go:120 +0xc4
  | github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).obsInvokeReceiver(0xc0004335f0, 0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0x0, 0xc000031d70, ...)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/transport/http/transport.go:500 +0x10f
  | github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).invokeReceiver(0xc0004335f0, 0x1706c00, 0xc0004242a0, 0x17379c0, 0xc0005000d0, 0x12f56e0, 0xc000121200, 0x1, 0x2, 0xffffffffffffffff, ...)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/transport/http/transport.go:484 +0xc5
  | github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP(0xc0004335f0, 0x1702d40, 0xc0001e00e0, 0xc0001d4000)
  | /go/pkg/mod/github.com/cloudevents/sdk-go@v0.10.0/pkg/cloudevents/transport/http/transport.go:592 +0xafb
  | net/http.(*ServeMux).ServeHTTP(0xc000226900, 0x1702d40, 0xc0001e00e0, 0xc0001d4000)
  | /usr/local/go/src/net/http/server.go:2387 +0x1bd
  | net/http.serverHandler.ServeHTTP(0xc0001e0000, 0x1702d40, 0xc0001e00e0, 0xc0001d4000)
  | /usr/local/go/src/net/http/server.go:2802 +0xa4
  | net/http.(*conn).serve(0xc0000ce000, 0x1706b40, 0xc0003ac000)
  | /usr/local/go/src/net/http/server.go:1890 +0x875
  | created by net/http.(*Server).Serve
  | /usr/local/go/src/net/http/server.go:2928 +0x384
```

**Comment by neox5** [comment] 2020-10-01 16:41
There is already a newer version available: [0.6.0](https://github.com/keptn-contrib/dynatrace-sli-service/releases/tag/0.6.0) 

Does this also happen with the newer version?

**Comment by luisr-escobar** [comment] 2020-10-01 17:19
just tried with [0.6.0](https://github.com/keptn-contrib/dynatrace-sli-service/releases/tag/0.6.0) and even though it doesn't error out it is not applying the filters added on the tiles and it is instead getting the metrics for all the entities for the metric specified on the SLI/SLO tile

**Comment by neox5** [comment] 2020-10-01 19:01
Then it's a duplicate of issue which I posted too. #95

**Comment by christian-kreuzberger-dtx** [comment] 2020-10-05 06:04
@grabnerandi can you take a look at this? Is this possible with the newest version?

**Comment by grabnerandi** [comment] 2020-10-05 06:57
Yes. I would consider this as a "missing implementation". I will take a look at it and implement it

**Comment by grabnerandi** [comment] 2020-10-07 09:20
Wanted to add to this that there is another issue that needs to be fixed with this as well. It is about how the dynatrace-sli-service creates the SLI.yaml for metrics that are split by dynatrace entities, e.g: services, hosts, user actions ...

This was brought up by one user in the keptn slack where the dynatrace-sli-service creates the following sli.yaml
```
ua_vc_CEP_HOME: "metricSelector=builtin:apps.web.action.visuallyComplete.load.browser:merge(1):percentile(50.000000):names:filter(eq(dt.entity.application_method,CEP Home));entitySelector=type(APPLICATION_METHOD),mzId(-6782011125623063524)"
```

it should however not use a filter for dt.entity objects but instead us it with the entitySelector like this
```
ua_vc_CEP_HOME: "metricSelector=builtin:apps.web.action.visuallyComplete.load.browser:merge(1):percentile(50.000000):names:filter(eq(dt.entity.application_method,CEP Home));entitySelector=type(APPLICATION_METHOD),entityId(APPLICATION_METHOD-11111111111111),mzId(-6782011125623063524)"
```

**Closed as completed** 2020-10-13 13:04 UTC
