### ISSUE TITLE
SLI-Service ignores filter of metric defintion

### ISSUE THREAD

**Issue by neox5** [keptn-contrib/dynatrace-sli-service#95] opened 2020-10-01 16:50 UTC
When the SLI-service parses a Dashboard for the Quality-Gate usecase it ignores the filters defined on a metric and takes all available entities.

In our case we wanted to filter one single service, which can be seen in the last section of the provided dashboard-json:

```json
{
    "metadata": {
        "configurationVersions": [3],
        "clusterVersion": "1.200.89.20200826-104932"
    },
    "id": "9786cacb-b172-4343-9dc7-84c8f42ae5d7",
  "dashboardMetadata": {
    "name": "KQG;project=myproj;service=myservice;stage=staging",
    "shared": false,
    "owner": "user",
    "sharingDetails": {
      "linkShared": true,
      "published": false
    },
    "dashboardFilter": {
      "timeframe": ""
    }
  },
    "tiles": [{
        "name": "Markdown",
        "tileType": "MARKDOWN",
        "configured": true,
        "bounds": {
            "top": 0,
            "left": 0,
            "width": 836,
            "height": 76
        },
        "tileFilter": {},
        "markdown": "KQG.Total.Pass=90%;KQG.Total.Warning=75%;KQG.Compare.WithScore=pass;KQG.Compare.Results=1;KQG.Compare.Function=avg\n"
    }, {
        "name": "",
        "tileType": "CUSTOM_CHARTING",
        "configured": true,
        "bounds": {
            "top": 114,
            "left": 0,
            "width": 836,
            "height": 456
        },
        "tileFilter": {},
        "filterConfig": {
            "type": "MIXED",
            "customName": "Server side response time | ;sli=median_response_time;pass=<+10%,<500;key=true",
            "defaultName": "Custom chart",
            "chartConfig": {
                "legendShown": true,
                "type": "TIMESERIES",
                "series": [{
                    "metric": "builtin:service.response.server",
                    "aggregation": "PERCENTILE",
                    "percentile": 50,
                    "type": "LINE",
                    "entityType": "SERVICE",
                    "dimensions": [{
                        "id": "0",
                        "name": "dt.entity.service",
                        "values": [],
                        "entityDimension": true
                    }],
                    "sortAscending": false,
                    "aggregationRate": "TOTAL",
                    "sortColumn": true
                }],
                "resultMetadata": {}
            },
            "filtersPerEntityType": {
                "SERVICE": {
                    "SPECIFIC_ENTITIES": ["SERVICE-2BDFB35714B81801"]
                }
            }
        }
    }]
}
```

Something like this was the result of the evaluation 😅
![column_of_death](https://user-images.githubusercontent.com/729071/94777172-4bca7e80-03c3-11eb-9086-a31239e228c6.png)

**Comment by christian-kreuzberger-dtx** [comment] 2020-10-05 06:04
Duplicate of #94

**Closed as completed by christian-kreuzberger-dtx** 2020-10-05 06:04 UTC
